export const LOAD_GENRES_START = "LOAD_GENRES_START";
export const LOAD_GENRES = "LOAD_GENRES";
export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
export const LOAD_GENRES_ERROR = "LOAD_GENRES_ERROR";

export const LOAD_ARTISTS_START = "LOAD_ARTISTS_START";
export const LOAD_ARTISTS = "LOAD_ARTISTS";
export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS";
export const LOAD_ARTISTS_ERROR = "LOAD_ARTISTS_ERROR";

export const LOAD_ARTIST_START = "LOAD_ARTIST_START";
export const LOAD_ARTIST = "LOAD_ARTIST";
export const LOAD_ARTIST_SUCCESS = "LOAD_ARTIST_SUCCESS";
export const LOAD_ARTIST_ERROR = "LOAD_ARTIST_ERROR";

export const LOAD_ALBUMS_START = "LOAD_ALBUMS_START";
export const LOAD_ALBUMS = "LOAD_ALBUMS";
export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS";
export const LOAD_ALBUMS_ERROR = "LOAD_ALBUMS_ERROR";
