export const LOAD_GENRES_START = "LOAD_GENRES_START"
export const LOAD_GENRES = "LOAD_GENRES"
export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS"
export const LOAD_GENRES_ERROR = "LOAD_GENRES_ERROR"

export const LOAD_ARTISTS_START = "LOAD_ARTISTS_START"
export const LOAD_ARTISTS = "LOAD_ARTISTS"
export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS"
export const LOAD_ARTISTS_ERROR = "LOAD_ARTISTS_ERROR"
